### ISSUE TITLE
Filter out expired items (optionally?) on get

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/Npgsql.DocumentDB#1]

**Comment by Revsgaard** [comment]
FoxIDs always need to filter out expired item. Therefore, maybe default filter out if optionally.

**Comment by bjornharrtell** [comment]
I opted to see this is as an non optional internal fix, done with https://github.com/bjornharrtell/PgKeyValueDB/commit/d4c154e19f1f33eb190992f65e7318b080b6f25c and https://github.com/bjornharrtell/PgKeyValueDB/commit/c4751e8739709fea2ad385bce8202f8b17e78604.

That is, API is unchanged and expired items should no longer be included in any result.

**Comment by bjornharrtell** [comment]
Released as 0.4.4.

**Comment by Revsgaard** [comment]
Perfect very nice, FoxIDs is updated to user the new version.
