### ISSUE TITLE
Naming of the GetSet and GetSetAsync methods 

### ISSUE THREAD

**Issue by Revsgaard** [bjornharrtell/Npgsql.DocumentDB#2]
The name GetSet sounds like data is both saved and loaded in the method. Maybe rename the methods to GetList and GetListAsync.

**Comment by Revsgaard** [comment]
@bjornharrtell considered renaming.

**Comment by bjornharrtell** [comment]
Hehe yes I was confused about them myself yesterday. But I don't like list either since they do return a set.

**Comment by Revsgaard** [comment]
What about GetHashSet or GetMany...

**Comment by bjornharrtell** [comment]
Both names are pretty good, now I have do decide which one of them.

**Comment by bjornharrtell** [comment]
GetHashSet it is https://github.com/bjornharrtell/PgKeyValueDB/commit/175794501faec6a762998d161028ef683dc237f9
